### PR TITLE
Fix blockchain name 

### PR DESCRIPTION
**Pull request by tequdev**
Fix blockchain name Ripple to XRPL.

### CODE REVIEW

**Comment by Perrier33** [comment]
True

**Comment by tequdev** [comment]
https://github.com/flare-labs-ltd/fassets/commit/a2bbbabb82b138648ad30e71ce907ab6e5a37bfc

**Comment by ilanDoron** [comment]
Hi
@develoQ 
why was it closed?

**Comment by tequdev** [comment]
> Hi
> 
> @develoQ 
> 
> why was it closed?
> 
> 

This fix was already applied by other commit.

**Comment by ilanDoron** [comment]
Ah
great

**Pull request closed without merging**
